#!/bin/sh

while getopts ":r:" opt; do
	case $opt in
		r) url=$OPTARG;;
		:) echo "Missing option argument for -$OPTARG >&2; exit 1;;
		*) echo "Unknown option: -$OPTARG >&2; exit 1;;
	esac
done

gst-launch-1.0 \
rtmpsrc location="$url live=1" \
! flvdemux \
! h264parse \
! omxh264dec \
! videoconvert \
! fbdevsink device=/dev/fb1 sync=false &

child="$!"

trap "kill $child" exit INT TERM

wait
