#!/bin/sh

while getopts ":r:" opt; do
	case $opt in
		r) url=$OPTARG;;
		:) echo "Missing option argument for -$OPTARG >&2; exit 1;;
		*) echo "Unknown option: -$OPTARG >&2; exit 1;;
	esac
done

fbcp &
fbcppid="$!"

omxplayer $url &
omxplayerpid="$!"
trap "kill $fbcppid $omxplayerpid" exit INT TERM

wait $omxplayerpid
